#!/usr/bin/python3
def best_score(a_dictionary):
    max = None 
    for k in a_dictionary:
        if a_dictionary[k] > max:
            max = a_dictionary[k]
        if max == None:
            return None
        else:
        return list(a_dictionary).index(max)
